# Use the official Node.js image
FROM node:20

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install frontend dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend code
COPY . .

# Expose the frontend development server port
EXPOSE 3000

# Command to run the React development server
CMD ["npm", "start"]
