version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    command: ["npx", "nodemon", "src/server.js"]  # Run your app using nodemon
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: sentimentanalysis
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - sentiment_analysis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - sentiment_analysis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sentimentanalysis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentiment_analysis

volumes:
  postgres_data:
networks:
  sentiment_analysis:
    driver: bridge
