version: "3.8"
services:
  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend  # Sync backend directory with the container
      - /app/backend/node_modules  # Prevent overwriting node_modules in the container
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: sentimentanalysis
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - sentiment_analysis

  frontend:
    restart: always
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend  # Sync frontend directory with the container
      - /app/frontend/node_modules  # Prevent overwriting node_modules in the container
    networks:
      - sentiment_analysis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sentimentanalysis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentiment_analysis

volumes:
  postgres_data:

networks:
  sentiment_analysis:
    driver: bridge
