# Use an official Node.js runtime as a parent image
FROM node:18
RUN apt-get update && apt-get install -y iputils-ping telnet
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install backend dependencies
RUN npm install --legacy-peer-deps

RUN npm install -g nodemon  # Install nodemon globally for hot reloading

# Copy the rest of the backend code
COPY . .

# Install nodemon globally for development
RUN npm install -g nodemon

# Expose the application port
EXPOSE 5001

# Command to run the app with nodemon
CMD ["npx", "nodemon", "src/server.js"]
