# Use an official Node.js runtime as a parent image
FROM node:18
RUN apt-get update && apt-get install -y iputils-ping telnet
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json for npm install
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --legacy-peer-deps


# Copy the rest of the application code
COPY . .

# Install nodemon globally for development
RUN npm install -g nodemon

# Expose the application port
EXPOSE 5001

# Command to run the app using nodemon
CMD ["npx", "nodemon", "server.js"]
