# Use the official Node.js image
FROM node:20

# Set the working directory inside the container
WORKDIR /app/backend

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install backend dependencies
RUN npm install
RUN npm install -g nodemon  # Install nodemon globally for hot reloading

# Copy the rest of the backend code
COPY . .

# Expose the backend port
EXPOSE 5000

# Command to run the app with nodemon
CMD ["npx", "nodemon", "src/server.js"]
